INSERT INTO products (id, name, description, category, brand, sku, base_price, stock, is_active, rating, tier, attributes) VALUES
(gen_random_uuid(), 'Cuaderno A4 Rayado 100 hojas', 'Cuaderno A4 rayado tapa blanda', 'Cuadernos', 'Alpha', 'CUA-A4-R100-ECO', 1490, 200, true, 3.2, 'economico', '{"tamano":"A4","tipo":"rayado","hojas":100,"tapa":"blanda"}'),
(gen_random_uuid(), 'Cuaderno A4 Rayado 100 hojas', 'Cuaderno A4 rayado tapa blanda', 'Cuadernos', 'Justus', 'CUA-A4-R100-MED', 2490, 150, true, 4.2, 'medio', '{"tamano":"A4","tipo":"rayado","hojas":100,"tapa":"blanda"}'),
(gen_random_uuid(), 'Cuaderno A4 Rayado 100 hojas', 'Cuaderno A4 rayado tapa dura', 'Cuadernos', 'Oxford', 'CUA-A4-R100-PRE', 4990, 80, true, 4.9, 'premium', '{"tamano":"A4","tipo":"rayado","hojas":100,"tapa":"dura"}'),
(gen_random_uuid(), 'Cuaderno A4 Rayado 50 hojas', 'Cuaderno A4 rayado 50 hojas', 'Cuadernos', 'Alpha', 'CUA-A4-R50-ECO', 990, 200, true, 3.0, 'economico', '{"tamano":"A4","tipo":"rayado","hojas":50,"tapa":"blanda"}'),
(gen_random_uuid(), 'Cuaderno A4 Rayado 200 hojas', 'Cuaderno A4 rayado tapa dura', 'Cuadernos', 'Oxford', 'CUA-A4-R200-PRE', 6990, 50, true, 4.8, 'premium', '{"tamano":"A4","tipo":"rayado","hojas":200,"tapa":"dura"}'),
(gen_random_uuid(), 'Cuaderno A4 Cuadriculado 100 hojas', 'Cuaderno A4 cuadriculado', 'Cuadernos', 'Alpha', 'CUA-A4-C100-ECO', 1490, 180, true, 3.2, 'economico', '{"tamano":"A4","tipo":"cuadriculado","hojas":100,"tapa":"blanda"}'),
(gen_random_uuid(), 'Cuaderno A4 Cuadriculado 100 hojas', 'Cuaderno A4 cuadriculado', 'Cuadernos', 'Justus', 'CUA-A4-C100-MED', 2690, 120, true, 4.3, 'medio', '{"tamano":"A4","tipo":"cuadriculado","hojas":100,"tapa":"blanda"}'),
(gen_random_uuid(), 'Cuaderno A4 Cuadriculado 100 hojas', 'Cuaderno A4 cuadriculado tapa dura', 'Cuadernos', 'Oxford', 'CUA-A4-C100-PRE', 5290, 60, true, 4.9, 'premium', '{"tamano":"A4","tipo":"cuadriculado","hojas":100,"tapa":"dura"}'),
(gen_random_uuid(), 'Cuaderno A4 Cuadriculado 200 hojas', 'Cuaderno A4 cuadriculado tapa dura', 'Cuadernos', 'Oxford', 'CUA-A4-C200-PRE', 7490, 40, true, 4.8, 'premium', '{"tamano":"A4","tipo":"cuadriculado","hojas":200,"tapa":"dura"}'),
(gen_random_uuid(), 'Cuaderno A3 Rayado 100 hojas', 'Cuaderno A3 grande rayado', 'Cuadernos', 'Justus', 'CUA-A3-R100-MED', 3990, 60, true, 4.1, 'medio', '{"tamano":"A3","tipo":"rayado","hojas":100,"tapa":"blanda"}'),
(gen_random_uuid(), 'Cuaderno A5 Rayado 80 hojas', 'Cuaderno A5 pequeno', 'Cuadernos', 'Alpha', 'CUA-A5-R80-ECO', 890, 250, true, 3.0, 'economico', '{"tamano":"A5","tipo":"rayado","hojas":80,"tapa":"blanda"}'),
(gen_random_uuid(), 'Cuaderno Triple Renglon 100 hojas', 'Cuaderno triple renglon para inicial', 'Cuadernos', 'Justus', 'CUA-TR-100-MED', 2290, 100, true, 4.4, 'medio', '{"tamano":"A4","tipo":"triple renglon","hojas":100,"tapa":"blanda"}'),
(gen_random_uuid(), 'Lapiz HB N2', 'Lapiz grafito HB basico', 'Lapices', 'Alpha', 'LAP-HB-ECO', 150, 500, true, 3.0, 'economico', '{"tipo":"grafito","dureza":"HB"}'),
(gen_random_uuid(), 'Lapiz HB N2', 'Lapiz grafito HB', 'Lapices', 'Faber-Castell', 'LAP-HB-MED', 350, 400, true, 4.3, 'medio', '{"tipo":"grafito","dureza":"HB"}'),
(gen_random_uuid(), 'Lapiz HB N2 Triangular', 'Lapiz ergonomico triangular', 'Lapices', 'Staedtler', 'LAP-HB-PRE', 790, 200, true, 4.8, 'premium', '{"tipo":"grafito","dureza":"HB","forma":"triangular"}'),
(gen_random_uuid(), 'Lapiz Rojo-Azul Bicolor', 'Lapiz bicolor', 'Lapices', 'Faber-Castell', 'LAP-BICO', 490, 200, true, 4.2, 'medio', '{"tipo":"bicolor"}'),
(gen_random_uuid(), 'Colores x12 Cortos', 'Lapices de colores 12 cortos', 'Colores', 'Alpha', 'COL-12C-ECO', 2490, 150, true, 3.0, 'economico', '{"unidades":12,"largo":"corto"}'),
(gen_random_uuid(), 'Colores x12 Largos', 'Lapices de colores 12 largos', 'Colores', 'Faber-Castell', 'COL-12L-MED', 4990, 120, true, 4.5, 'medio', '{"unidades":12,"largo":"largo"}'),
(gen_random_uuid(), 'Colores x12 Largos Premium', 'Lapices de colores profesionales', 'Colores', 'Faber-Castell', 'COL-12L-PRE', 8990, 60, true, 4.9, 'premium', '{"unidades":12,"largo":"largo"}'),
(gen_random_uuid(), 'Colores x24 Largos', 'Lapices de colores 24', 'Colores', 'Faber-Castell', 'COL-24L-MED', 7990, 80, true, 4.5, 'medio', '{"unidades":24,"largo":"largo"}'),
(gen_random_uuid(), 'Borrador Blanco', 'Goma de borrar basica', 'Accesorios', 'Alpha', 'BOR-ECO', 290, 400, true, 3.0, 'economico', '{}'),
(gen_random_uuid(), 'Borrador Blanco', 'Goma de borrar suave', 'Accesorios', 'Pelikan', 'BOR-MED', 590, 300, true, 4.2, 'medio', '{}'),
(gen_random_uuid(), 'Borrador Blanco Premium', 'Goma sin residuos', 'Accesorios', 'Staedtler', 'BOR-PRE', 990, 150, true, 4.8, 'premium', '{}'),
(gen_random_uuid(), 'Regla 30cm', 'Regla plastica 30cm', 'Accesorios', 'Alpha', 'REG-30-ECO', 190, 400, true, 3.0, 'economico', '{"medida":"30cm"}'),
(gen_random_uuid(), 'Regla 30cm', 'Regla irrompible 30cm', 'Accesorios', 'Maped', 'REG-30-MED', 590, 250, true, 4.3, 'medio', '{"medida":"30cm"}'),
(gen_random_uuid(), 'Tajador Simple', 'Tajador basico', 'Accesorios', 'Alpha', 'TAJ-ECO', 190, 500, true, 3.0, 'economico', '{}'),
(gen_random_uuid(), 'Tajador Doble con Deposito', 'Tajador doble con deposito', 'Accesorios', 'Maped', 'TAJ-MED', 690, 200, true, 4.4, 'medio', '{}'),
(gen_random_uuid(), 'Tijera Punta Redonda 13cm', 'Tijera escolar', 'Accesorios', 'Alpha', 'TIJ-ECO', 990, 200, true, 3.0, 'economico', '{}'),
(gen_random_uuid(), 'Tijera Punta Redonda 13cm', 'Tijera escolar', 'Accesorios', 'Maped', 'TIJ-MED', 1990, 150, true, 4.3, 'medio', '{}'),
(gen_random_uuid(), 'Goma en Barra 20g', 'Pegamento en barra 20g', 'Pegamentos', 'Alpha', 'PEG-20-ECO', 590, 300, true, 3.0, 'economico', '{"peso":"20g"}'),
(gen_random_uuid(), 'Goma en Barra 40g', 'Pegamento en barra 40g', 'Pegamentos', 'Pritt', 'PEG-40-MED', 1290, 200, true, 4.5, 'medio', '{"peso":"40g"}'),
(gen_random_uuid(), 'Goma en Barra 40g Premium', 'Pegamento extra fuerte', 'Pegamentos', 'UHU', 'PEG-40-PRE', 2190, 100, true, 4.8, 'premium', '{"peso":"40g"}'),
(gen_random_uuid(), 'Block Dibujo A4 20 hojas', 'Block de dibujo A4', 'Arte', 'Alpha', 'BLK-A4-ECO', 1490, 150, true, 3.0, 'economico', '{"tamano":"A4","hojas":20}'),
(gen_random_uuid(), 'Block Dibujo A4 30 hojas', 'Block de dibujo A4', 'Arte', 'Canson', 'BLK-A4-MED', 2990, 90, true, 4.5, 'medio', '{"tamano":"A4","hojas":30}'),
(gen_random_uuid(), 'Temperas x12', 'Set temperas 12 colores', 'Arte', 'Alpha', 'TEM-12-ECO', 3990, 100, true, 3.2, 'economico', '{"colores":12}'),
(gen_random_uuid(), 'Temperas x12', 'Set temperas 12 colores', 'Arte', 'Giotto', 'TEM-12-MED', 6990, 60, true, 4.6, 'medio', '{"colores":12}'),
(gen_random_uuid(), 'Plasticina x12', 'Plasticina 12 barras', 'Arte', 'Alpha', 'PLS-12-ECO', 1990, 120, true, 3.0, 'economico', '{"colores":12}'),
(gen_random_uuid(), 'Plasticina x12', 'Plasticina 12 barras suave', 'Arte', 'Giotto', 'PLS-12-MED', 3490, 80, true, 4.5, 'medio', '{"colores":12}'),
(gen_random_uuid(), 'Crayones x12 Gruesos', 'Crayones gruesos para inicial', 'Arte', 'Alpha', 'CRA-12-ECO', 2490, 100, true, 3.2, 'economico', '{"colores":12}'),
(gen_random_uuid(), 'Crayones x12 Gruesos Lavables', 'Crayones gruesos lavables', 'Arte', 'Crayola', 'CRA-12-PRE', 5990, 50, true, 4.8, 'premium', '{"colores":12}'),
(gen_random_uuid(), 'Plumones x12 Punta Fina', 'Plumones punta fina', 'Arte', 'Alpha', 'PLU-12F-ECO', 2990, 100, true, 3.0, 'economico', '{"colores":12}'),
(gen_random_uuid(), 'Plumones x12 Punta Fina', 'Plumones punta fina lavables', 'Arte', 'Faber-Castell', 'PLU-12F-MED', 5990, 70, true, 4.5, 'medio', '{"colores":12}'),
(gen_random_uuid(), 'Plumones x12 Punta Gruesa', 'Plumones punta gruesa', 'Arte', 'Faber-Castell', 'PLU-12G-MED', 6490, 60, true, 4.4, 'medio', '{"colores":12}'),
(gen_random_uuid(), 'Folder Manila A4 x10', 'Folders manila paquete', 'Folders', 'Alpha', 'FOL-MAN', 490, 200, true, 3.0, 'economico', '{}'),
(gen_random_uuid(), 'Folder Plastico A4', 'Folder plastico con fastener', 'Folders', 'Artesco', 'FOL-PLA', 290, 300, true, 4.0, 'medio', '{}'),
(gen_random_uuid(), 'Papel Bond A4 x500', 'Resma papel bond A4', 'Papeleria', 'Atlas', 'PAP-A4', 1290, 100, true, 4.0, 'medio', '{}'),
(gen_random_uuid(), 'Forro Transparente A4 x5', 'Forro adhesivo transparente', 'Forros', 'Vinifan', 'FOR-TRANS', 490, 200, true, 4.2, 'medio', '{}'),
(gen_random_uuid(), 'Forro de Color A4 x5', 'Forro adhesivo de colores', 'Forros', 'Vinifan', 'FOR-COLOR', 590, 150, true, 4.0, 'medio', '{}');
